# 白名单不进行拦截的路径
security:
  white-list:
    - /error
    - /css/**
    - /js/**
    - /webjars/**
    - /favicon.ico
    - /.well-known/**
    - /hello/**
    - /user/login
    - /user/register
    - /user/getUserPageData
server:
  port: 8090
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
aliyun:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  uKeyId: ${ALIYUN_ACCESS_KEY_ID}
  uKeySecret: ${ALIYUN_ACCESS_KEY_SECRET}
  bucketName: yang199-big-event
jwt:
  secret-key: VbM5f7NtItTlDPfwMBclhmrZ4tTx5OQD
  ttl: 7200000
  token-name: Authorization



